//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片交易金(元).
        /// </summary>
        internal static string CardReward {
            get {
                return ResourceManager.GetString("CardReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 签到交易金(元).
        /// </summary>
        internal static string DailySign {
            get {
                return ResourceManager.GetString("DailySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模拟收益交易金(元).
        /// </summary>
        internal static string DemoProfit {
            get {
                return ResourceManager.GetString("DemoProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册交易金(元).
        /// </summary>
        internal static string DemoRegister {
            get {
                return ResourceManager.GetString("DemoRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模拟下单交易金(元).
        /// </summary>
        internal static string DemoTransaction {
            get {
                return ResourceManager.GetString("DemoTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首日入金交易金(元).
        /// </summary>
        internal static string FirstDeposit {
            get {
                return ResourceManager.GetString("FirstDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码错误.
        /// </summary>
        internal static string INVALID_VERIFY_CODE {
            get {
                return ResourceManager.GetString("INVALID_VERIFY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开户交易金(元).
        /// </summary>
        internal static string LiveRegister {
            get {
                return ResourceManager.GetString("LiveRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 竞猜盈利交易金(元).
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邀请好友交易金(元).
        /// </summary>
        internal static string ReferralReward {
            get {
                return ResourceManager.GetString("ReferralReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片点赞积分.
        /// </summary>
        internal static string ScoreLike {
            get {
                return ResourceManager.GetString("ScoreLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实盘下单积分.
        /// </summary>
        internal static string ScoreLiveOrder {
            get {
                return ResourceManager.GetString("ScoreLiveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获得打赏积分.
        /// </summary>
        internal static string ScoreReward {
            get {
                return ResourceManager.GetString("ScoreReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片分享积分.
        /// </summary>
        internal static string ScoreShare {
            get {
                return ResourceManager.GetString("ScoreShare", resourceCulture);
            }
        }
    }
}
